![title](http://www.earthserver.eu/sites/default/files/cube-wallpaper_mr.jpg)

### My goal:

I wanna create data cube and use [numpy](http://www.numpy.org/) for it.

### What is data cube?

In computer programming contexts, a **data cube (*or datacube*)** is a multi-dimensional ("n-D") array of values. Typically, the term datacube is applied in contexts where these arrays are massively larger than the hosting computer's main memory; examples include multi-Terabyte/Petabyte data warehouses and time series of image data. [Read more...](https://en.wikipedia.org/wiki/Data_cube)

### 1. Import

In [29]:
import numpy as np

### 2. How do you create a 3D array (data cube) in python?

[Source](https://stackoverflow.com/questions/42709221/how-do-you-create-a-3d-array-data-cube-in-python)

numpy.**arange**(*(start, )stop, (step, ),dtype=None*)

Return evenly spaced values within a given interval. [More...](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)

In [30]:
x = np.arange(7)
x

array([0, 1, 2, 3, 4, 5, 6])

In [31]:
y = np.arange(0,30,10)
y

array([ 0, 10, 20])

In [32]:
z = np.arange(0,200,100)
z

array([  0, 100])

**meshgrid** as its name suggests creates an orthogonal mesh. If you call it with 3 arguments it will be a 3d mesh. Now the mesh is 3d arrangement of points but each point has 3 coordinates. Therefore meshgrid returns 3 arrays one for each coordinate.

The standard way of getting one 3d array out of that is to apply a vectorised function with three arguments. Here is a simple example:

In [33]:
ym, zm, xm = np.meshgrid(y, z, x)

In [34]:
print(ym.shape)
ym

(2, 3, 7)


array([[[ 0,  0,  0,  0,  0,  0,  0],
        [10, 10, 10, 10, 10, 10, 10],
        [20, 20, 20, 20, 20, 20, 20]],

       [[ 0,  0,  0,  0,  0,  0,  0],
        [10, 10, 10, 10, 10, 10, 10],
        [20, 20, 20, 20, 20, 20, 20]]])

In [35]:
print(zm.shape)
zm

(2, 3, 7)


array([[[  0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0]],

       [[100, 100, 100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100, 100, 100]]])

In [36]:
print(xm.shape)
xm

(2, 3, 7)


array([[[0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6]],

       [[0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6]]])